Repository paritytech/parity-zcash, pull requests merged in 2018-12, with the labels that each got.

#9 Storing and updating join split nullifers
  db/src/block_chain_db.rs
  db/src/kv/memorydb.rs
  db/src/kv/transaction.rs
  primitives/src/hash.rs
  storage/src/block_impls.rs
  storage/src/error.rs
  storage/src/lib.rs
  storage/src/nullifier.rs
  storage/src/store.rs
Labels: A8-looksgood 🦄

#14 Precompute sighash for joinsplit/sapling validation
  script/src/lib.rs
  verification/src/accept_transaction.rs
Labels: A0-pleasereview 🤓

#18 Update README
  README.md
Labels: A0-pleasereview 🤓

#19 Split json-rpc and cli docs from readme
  CLI.md
  JSON-RPC.md
  README.md
Labels: A0-pleasereview 🤓

#20 Update travis secret
  .travis.yml
Labels: A2-insubstantial 👶

#21 Sapling verifying keys
  Cargo.lock
  chain/src/block.rs
  chain/src/transaction.rs
  crypto/Cargo.toml
  crypto/src/json/groth16.rs
  crypto/src/json/mod.rs
  crypto/src/json/pghr13.rs
  crypto/src/lib.rs
  message/src/common/inventory.rs
  network/src/consensus.rs
  res/sapling-output-verifying-key.json
  res/sapling-spend-verifying-key.json
  verification/Cargo.toml
  verification/src/accept_transaction.rs
  verification/src/lib.rs
  verification/src/sapling.rs
Labels: A8-looksgood 🦄

#23 Version + expiry_height checks in accept_transaction
  network/src/consensus.rs
  test-data/src/chain_builder.rs
  verification/src/accept_transaction.rs
  verification/src/chain_verifier.rs
  verification/src/error.rs
Labels: A0-pleasereview 🤓

#24 Block founders reward
  Cargo.lock
  keys/src/address.rs
  keys/src/keypair.rs
  miner/src/block_assembler.rs
  network/Cargo.toml
  network/src/consensus.rs
  network/src/lib.rs
  rpc/src/v1/impls/blockchain.rs
  rpc/src/v1/impls/raw.rs
  rpc/src/v1/types/address.rs
  rpc/src/v1/types/get_tx_out_response.rs
  rpc/src/v1/types/transaction.rs
  script/src/script.rs
  script/src/sign.rs
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_verifier.rs
  test-data/Cargo.toml
  test-data/src/block.rs
  test-data/src/lib.rs
  verification/Cargo.toml
  verification/src/accept_block.rs
  verification/src/chain_verifier.rs
  verification/src/error.rs
  verification/src/lib.rs
  verification/src/work.rs
Labels: A0-pleasereview 🤓

#26 Fix required work calculation on testnet
  bencher/src/verifier.rs
  miner/src/block_assembler.rs
  network/src/consensus.rs
  network/src/network.rs
  sync/src/synchronization_verifier.rs
  verification/src/accept_chain.rs
  verification/src/accept_header.rs
  verification/src/chain_verifier.rs
  verification/src/lib.rs
  verification/src/work.rs
  verification/src/work_zcash.rs
Labels: A0-pleasereview 🤓

#29 SHA-256 compress
  Cargo.lock
  crypto/Cargo.toml
  crypto/src/lib.rs
Labels: A0-pleasereview 🤓
