Repository paritytech/parity-zcash, pull requests merged in 2019-04, with the labels that each got.

#67 Verify headers in separate thread
  sync/src/blocks_writer.rs
  sync/src/lib.rs
  sync/src/local_node.rs
  sync/src/synchronization_client.rs
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_verifier.rs
  sync/src/utils/message_block_headers_provider.rs
  sync/src/utils/mod.rs
  verification/src/chain_verifier.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#69 Actually verify headers
  sync/src/synchronization_client.rs
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_verifier.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#70 Do not verify headers twice during synchronization
  Cargo.lock
  bencher/src/verifier.rs
  pzec/config.rs
  sync/src/blocks_writer.rs
  sync/src/synchronization_chain.rs
  sync/src/synchronization_client.rs
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_verifier.rs
  sync/src/utils/best_headers_chain.rs
  verification/Cargo.toml
  verification/src/accept_transaction.rs
  verification/src/chain_verifier.rs
  verification/src/lib.rs
  verification/src/verify_chain.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#71 Disable TransactionDoubleSpend for coinbase transactions
  verification/src/accept_transaction.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#72 Cache transaction outputs in ChainAcceptor
  storage/src/lib.rs
  storage/src/transaction_provider.rs
  verification/src/accept_chain.rs
  verification/src/chain_verifier.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#74 Hash header(s) without holding sync lock
  sync/src/inbound_connection.rs
  sync/src/local_node.rs
  sync/src/synchronization_client.rs
  sync/src/synchronization_client_core.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#73 Name all spawned threads
  p2p/src/p2p.rs
  sync/src/lib.rs
  sync/src/synchronization_verifier.rs
Labels: A2-insubstantial 👶, M4-core ⛓

#78 Handle reorganizations during blocks import
  db/src/block_chain_db.rs
  sync/src/blocks_writer.rs
  sync/src/lib.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#77 PGHR13 proofs verification
  Cargo.lock
  chain/src/lib.rs
  crypto/src/json/pghr13.rs
  crypto/src/lib.rs
  crypto/src/pghr13.rs
  network/src/consensus.rs
  storage/src/tree_state.rs
  storage/src/tree_state_provider.rs
  verification/Cargo.toml
  verification/src/accept_chain.rs
  verification/src/accept_transaction.rs
  verification/src/chain_verifier.rs
  verification/src/error.rs
  verification/src/lib.rs
  verification/src/sprout.rs
  verification/src/tree_cache.rs
Labels: A0-pleasereview 🤓

#83 Ignore zero-filled gaps in blk files
  import/src/block.rs
  serialization/src/reader.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#86 Improve error reporting in import handler
  pzec/commands/import.rs
Labels: A2-insubstantial 👶

#87 Fixed sapling sighash cache usage
  script/Cargo.toml
  script/src/sign.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#88 Fixed fee calculation in BlockCoinbaseMinerReward
  test-data/src/lib.rs
  verification/src/accept_block.rs
  verification/src/error.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#90 Unify transaction fee computation
  miner/src/fee.rs
  verification/src/accept_block.rs
  verification/src/accept_transaction.rs
  verification/src/error.rs
  verification/src/fee.rs
  verification/src/lib.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#92 Changed type of sighash cache
  script/src/interpreter.rs
  script/src/sign.rs
  script/src/verify.rs
  verification/src/accept_transaction.rs
  verification/src/sapling.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#94 Move some crypto stuff to bn library
  Cargo.lock
  crypto/src/pghr13.rs
Labels: A2-insubstantial 👶

#99 Fixed panic when header is verifying for (Verifying | Stored) block
  sync/src/synchronization_chain.rs
  sync/src/synchronization_client_core.rs
  verification/src/chain_verifier.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#100 Use empty value as false in comparison ops
  script/src/interpreter.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#81 Groth16 proofs verification
  Cargo.lock
  chain/src/join_split.rs
  crypto/src/groth16.rs
  crypto/src/json/groth16.rs
  crypto/src/lib.rs
  network/src/consensus.rs
  res/sprout-groth16-key.json
  verification/src/accept_transaction.rs
  verification/src/sprout.rs
Labels: A0-pleasereview 🤓
