Repository paritytech/parity-zcash, pull requests merged in 2019-03, with the labels that each got.

#46 Some preparations for Sapling note commitment tree
  Cargo.lock
  crypto/Cargo.toml
  crypto/src/lib.rs
  db/src/block_chain_db.rs
  db/src/kv/memorydb.rs
  db/src/kv/transaction.rs
  miner/src/block_assembler.rs
  storage/src/lib.rs
  storage/src/tree_state.rs
  storage/src/tree_state_provider.rs
  verification/Cargo.toml
  verification/src/lib.rs
  verification/src/sapling.rs
Labels: A0-pleasereview 🤓

#47 Update + read + verfiy sapling commitment tree where required
  db/src/block_chain_db.rs
  db/src/kv/memorydb.rs
  db/src/kv/mod.rs
  db/src/kv/transaction.rs
  miner/src/block_assembler.rs
  rpc/src/v1/impls/miner.rs
  storage/src/lib.rs
  storage/src/nullifier.rs
  storage/src/nullifier_tracker.rs
  storage/src/store.rs
  storage/src/tree_state.rs
  storage/src/tree_state_provider.rs
  sync/src/local_node.rs
  test-data/src/block.rs
  verification/src/accept_block.rs
  verification/src/accept_chain.rs
  verification/src/accept_transaction.rs
  verification/src/error.rs
Labels: A0-pleasereview 🤓

#49 Do not store sapling commitment tree root aside from the header
  db/src/block_chain_db.rs
  db/src/kv/memorydb.rs
  db/src/kv/mod.rs
  db/src/kv/transaction.rs
Labels: A0-pleasereview 🤓

#51 Cleanup some code + documentation
  JSON-RPC.md
  README.md
  db/src/block_chain_db.rs
  miner/src/block_assembler.rs
  network/src/network.rs
  script/src/flags.rs
  script/src/interpreter.rs
  script/src/opcode.rs
  script/src/script.rs
  storage/src/lib.rs
  storage/src/store.rs
  verification/src/accept_block.rs
  verification/src/accept_transaction.rs
  verification/src/sigops.rs
  verification/src/verify_block.rs
  verification/src/verify_transaction.rs
Labels: A0-pleasereview 🤓

#52 Fixed script iteration in bloom filter
  sync/src/utils/bloom_filter.rs
Labels: A0-pleasereview 🤓

#55 Add source for externsion field algo
  crypto/src/pghr13.rs
Labels: A2-insubstantial 👶

#57 Changed max number of headers in the headers message
  message/src/types/getheaders.rs
  message/src/types/headers.rs
  message/src/types/mod.rs
  sync/src/synchronization_server.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#59 Minimize chain structures hashing (part#1)
  bencher/Cargo.toml
  chain/Cargo.toml
  chain/src/indexed_block.rs
  chain/src/indexed_header.rs
  chain/src/indexed_transaction.rs
  miner/src/block_assembler.rs
  miner/src/memory_pool.rs
  p2p/src/lib.rs
  p2p/src/protocol/mod.rs
  p2p/src/protocol/sync.rs
  pzec/util.rs
  rpc/src/v1/impls/blockchain.rs
  rpc/src/v1/impls/raw.rs
  sync/Cargo.toml
  sync/src/inbound_connection.rs
  sync/src/lib.rs
  sync/src/local_node.rs
  sync/src/synchronization_chain.rs
  sync/src/synchronization_client.rs
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_server.rs
  sync/src/synchronization_verifier.rs
  sync/src/types.rs
  sync/src/utils/synchronization_state.rs
  verification/Cargo.toml
  verification/src/chain_verifier.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#61 Penalize peer when receiving unknown headers message
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_manager.rs
  sync/src/synchronization_peers_tasks.rs
Labels: A0-pleasereview 🤓, M4-core ⛓

#63 Minimize chain structures hashing (part#2)
  bencher/src/database.rs
  chain/README.md
  chain/src/block.rs
  chain/src/block_header.rs
  chain/src/indexed_header.rs
  chain/src/indexed_transaction.rs
  chain/src/lib.rs
  chain/src/transaction.rs
  db/src/block_chain_db.rs
  miner/src/memory_pool.rs
  network/src/network.rs
  pzec/commands/rollback.rs
  pzec/util.rs
  rpc/src/v1/impls/blockchain.rs
  storage/src/block_ancestors.rs
  storage/src/block_iterator.rs
  storage/src/block_provider.rs
  storage/src/lib.rs
  storage/src/store.rs
  storage/src/transaction_provider.rs
  sync/src/synchronization_chain.rs
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_executor.rs
  sync/src/synchronization_server.rs
  sync/src/utils/message_block_headers_provider.rs
  verification/src/deployments.rs
  verification/src/timestamp.rs
  verification/src/work.rs
Labels: A0-pleasereview 🤓

#65 Optimize equihash implementation
  verification/src/equihash.rs
Labels: A0-pleasereview 🤓
